
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: sanders-first-app-development


test:
  <<: *default
  database: sanders-first-app-test

production:
  <<: *default
  database: sanders-first-app
